# SPDX-FileCopyrightText: Copyright 2026 Siemens AG
# SPDX-License-Identifier: Apache-2.0

"""TPM attestation formats."""

from libattest.formats.tpm.attestation_params import (
    TpmAttestationParamsASN1,
    attestation_params_from_response_info,
    attestation_params_request_info,
    attestation_params_response_info,
    decode_tpm_attestation_params,
    encode_tpm_attestation_params,
    make_pcr_selection_resp_info,
)
from libattest.formats.tpm.pcr_selection import (
    TPM_PCR_SELECTION_OID_DEFAULT,
    TPM_PCR_SELECTION_OID_ENV,
    TpmPcrSelectionInfoASN1,
    build_tpm_pcr_selection_json,
    decode_tpm_pcr_selection_info,
    encode_tpm_pcr_selection_info,
    encode_tpm_pcr_selection_info_from_parts,
    pcr_selection_from_response_info,
    pcr_selection_response_info,
    resolve_tpm_pcr_selection_oid,
    tpm_pcr_selection_json_value,
)
from libattest.formats.tpm.tcg import (
    TcgAttestCertify,
    decode_tcg_attest_certify,
    id_tcg_attest_certify,
    id_tcg_attest_quote,
    prepare_tcg_attest_certify,
)
from libattest.formats.tpm.tpms_attest import (
    TPM_ALG_ECDSA,
    TPM_ALG_RSAPSS,
    TPM_ALG_RSASSA,
    TPM_ALG_SHA1,
    TPM_ALG_SHA256,
    TPM_ALG_SHA384,
    TPM_ALG_SHA512,
    TPM_GENERATED_VALUE,
    TPM_ST_ATTEST_QUOTE,
    ParsedAttest,
    TpmQuoteSignatureEvidence,
    parse_tpms_attest,
    pcr_indices_to_mask,
    pcr_mask_to_indices,
)

__all__ = [
    "TPM_ALG_ECDSA",
    "TPM_ALG_RSAPSS",
    "TPM_ALG_RSASSA",
    "TPM_ALG_SHA1",
    "TPM_ALG_SHA256",
    "TPM_ALG_SHA384",
    "TPM_ALG_SHA512",
    "TPM_GENERATED_VALUE",
    "TPM_PCR_SELECTION_OID_DEFAULT",
    "TPM_PCR_SELECTION_OID_ENV",
    "TPM_ST_ATTEST_QUOTE",
    "TcgAttestCertify",
    "TpmAttestationParamsASN1",
    "TpmPcrSelectionInfoASN1",
    "TpmQuoteSignatureEvidence",
    "attestation_params_from_response_info",
    "attestation_params_request_info",
    "attestation_params_response_info",
    "build_tpm_pcr_selection_json",
    "decode_tcg_attest_certify",
    "decode_tpm_attestation_params",
    "decode_tpm_pcr_selection_info",
    "encode_tpm_attestation_params",
    "encode_tpm_pcr_selection_info",
    "encode_tpm_pcr_selection_info_from_parts",
    "id_tcg_attest_certify",
    "id_tcg_attest_quote",
    "make_pcr_selection_resp_info",
    "ParsedAttest",
    "parse_tpms_attest",
    "pcr_indices_to_mask",
    "pcr_mask_to_indices",
    "pcr_selection_from_response_info",
    "pcr_selection_response_info",
    "prepare_tcg_attest_certify",
    "resolve_tpm_pcr_selection_oid",
    "tpm_pcr_selection_json_value",
]
