# SPDX-FileCopyrightText: Copyright 2026 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0

"""TPM key-attestation structures and signature-only PoP helpers."""

from libattest.formats.key_attest_pop.pop import (
    build_ecdsa_sha256_algorithm,
    build_sha256_rsa_algorithm,
    compute_key_attest_pop,
    verify_key_attest_pop,
)
from libattest.formats.key_attest_pop.structures import (
    DEFAULT_KEY_ATTEST_CHALL_OID,
    DEFAULT_KEY_ATTEST_POP_OID,
    DEFAULT_KEY_ATTEST_RESP_OID,
    ID_ECDSA_WITH_SHA256,
    ID_SHA256_WITH_RSA_ENCRYPTION,
    KEY_ATTEST_CHALL_OID_ENV,
    KEY_ATTEST_POP_OID_ENV,
    KEY_ATTEST_RESP_OID_ENV,
    KeyAttestChall,
    KeyAttestPoP,
    KeyAttestResp,
    VerifierMakeCredentialRequest,
    VerifierMakeCredentialResult,
    decode_key_attest_chall,
    decode_key_attest_pop,
    decode_key_attest_resp,
    encode_to_der,
    key_attest_chall_ak_name,
    key_attest_chall_ek_cert_chain,
    key_attest_chall_json_value,
    key_attest_pop_algorithm_oid,
    key_attest_pop_signature,
    key_attest_resp_enc_secret,
    key_attest_resp_enc_seed,
    key_attest_resp_json_value,
    prepare_key_attest_chall,
    prepare_key_attest_pop,
    prepare_key_attest_resp,
    resolve_key_attest_chall_oid,
    resolve_key_attest_pop_oid,
    resolve_key_attest_resp_oid,
    verifier_make_credential_request_to_json,
    verifier_make_credential_result_from_json,
    verifier_make_credential_result_to_json,
)

__all__ = [
    "DEFAULT_KEY_ATTEST_CHALL_OID",
    "DEFAULT_KEY_ATTEST_POP_OID",
    "DEFAULT_KEY_ATTEST_RESP_OID",
    "ID_ECDSA_WITH_SHA256",
    "ID_SHA256_WITH_RSA_ENCRYPTION",
    "KEY_ATTEST_CHALL_OID_ENV",
    "KEY_ATTEST_POP_OID_ENV",
    "KEY_ATTEST_RESP_OID_ENV",
    "KeyAttestChall",
    "KeyAttestPoP",
    "KeyAttestResp",
    "VerifierMakeCredentialRequest",
    "VerifierMakeCredentialResult",
    "build_ecdsa_sha256_algorithm",
    "build_sha256_rsa_algorithm",
    "compute_key_attest_pop",
    "decode_key_attest_chall",
    "decode_key_attest_pop",
    "decode_key_attest_resp",
    "encode_to_der",
    "key_attest_chall_ak_name",
    "key_attest_chall_ek_cert_chain",
    "key_attest_chall_json_value",
    "key_attest_pop_algorithm_oid",
    "key_attest_pop_signature",
    "key_attest_resp_enc_secret",
    "key_attest_resp_enc_seed",
    "key_attest_resp_json_value",
    "prepare_key_attest_chall",
    "prepare_key_attest_pop",
    "prepare_key_attest_resp",
    "resolve_key_attest_chall_oid",
    "resolve_key_attest_pop_oid",
    "resolve_key_attest_resp_oid",
    "verifier_make_credential_request_to_json",
    "verifier_make_credential_result_from_json",
    "verifier_make_credential_result_to_json",
    "verify_key_attest_pop",
]
